### ISSUE TITLE
pre commit file is missing (on windows)

### ISSUE THREAD

**Issue by simon-at-fugu** [lvoegtlin/pocr#2]
File "\apps\python\3.8.0\lib\site-packages\pocr\controller.py", line 117, in create
    shutil.copy(pkg_resources.resource_stream(__name__, Paths.PACKAGE_GIT_HOOK_PATH)
...
No such file or directory: '\\apps\\python\\3.8.0\\lib\\site-packages\\pocr\\utils\\pre-commit

**Comment by lvoegtlin** [comment]
I will check that later this afternoon
